sequenceDiagram
    autonumber
    actor CS_Role as CS / Agent / Reservasi
    participant Sistem as Sistem Aplikasi
    
    CS_Role->>Sistem: 1. Masuk ke Menu "Reservasi Tiket"
    CS_Role->>Sistem: 2. Memilih "Tanggal" dan "Kantor Keberangkatan"
    Sistem-->>CS_Role: Menampilkan Gambar Layout Peta Kursi Bus
    CS_Role->>Sistem: 3. Meng-klik "Nomor Bangku" (Misal: 4A)
    Note right of Sistem: Sistem mengunci sementara (Lock)<br/>bangku 4A agar tidak bisa dibeli pihak lain
    CS_Role->>Sistem: 4. Mengetik "Nama Pelanggan" & "Nomor HP"
    CS_Role->>Sistem: 5. Klik Tombol "Hitung Harga"
    Sistem-->>CS_Role: Menampilkan Harga Total & Tambahan (Tuslah)
    CS_Role->>Sistem: 6. Memilih Metode Bayar (Transfer/Tunai/DP)
    CS_Role->>Sistem: 7. Klik "Lunas / Cetak Tiket"
    Sistem-->>CS_Role: Status Tiket Sukses (Paid) & Cetak Struk
