sequenceDiagram
    autonumber
    actor Kasir as CASHIER (Loket Operasional)
    actor Supir as Supir Bus
    participant Sistem as Keuangan
    actor Fin as FINANCE (Pusat)

    Kasir->>Sistem: 1. Menu "Uang Saku": Ketik Uang Bekal Awal Supir
    Kasir->>Supir: 2. Memberi Uang Tunai Untuk Perjalanan
    Note over Supir, Kasir: (Waktu Berlalu - Perjalanan Selesai)
    Supir-->>Kasir: 3. Kembali ke Garasi Menyerahkan Bon
    Kasir->>Sistem: 4. Menu "Realisasi": Mengisi Kolom Nominal "BBM", "Tol"
    Kasir->>Sistem: 5. Klik "Simpan Draf Akhir"
    Fin->>Sistem: 6. Buka Menu "Verifikasi Buku Keuangan" (Ledger)
    Fin->>Sistem: 7. Mengecek Silang Bon Supir & Ketikan CASHIER
    Fin->>Sistem: 8. Klik Tombol "Setujui Transaksi" (Posting)
    Note right of Sistem: Saldo Perusahaan dipotong secara permanen<br/>dan Sah dimasukkan ke Pembukuan Pusat.
