sequenceDiagram
    autonumber
    actor SA as Superadmin
    actor ADM as ADMIN (Operasional)
    participant Sistem as Sistem Aplikasi
    
    SA->>Sistem: 1. Masuk ke Menu "Master Armada & Rute"
    Sistem-->>SA: Menyimpan Pilihan Bus & Jalur
    ADM->>Sistem: 2. Buka Menu "Penjadwalan (Tambah)"
    ADM->>Sistem: 3. Memilih "Rute" & Menyusun "Rentang Tanggal"
    ADM->>Sistem: 4. Klik Tombol "Generate Jadwal"
    Note right of Sistem: Sistem memecah rentang waktu<br/>menjadi jadwal harian dan armada bus satuan
    Sistem-->>ADM: Menampilkan Kalender Bus Harian
    ADM->>Sistem: 5. Buka Detail "Tiap Tanggal (Jadwal Harian)"
    ADM->>Sistem: 6. Masukkan "Nama Supir" ke Kolom Sopir
    ADM->>Sistem: 7. Klik Simpan
    Note right of Sistem: Jadwal diubah berstatus "Siap Dipesan"<br/>dan mulai muncul di layar loket.
