sequenceDiagram
    participant Sys as System Hook
    participant DB as MongoDB (DW)
    participant Mgt as Management / Superadmin
    participant API as Backend API

    Note left of Sys: Berjalan instan saat Transaksi PAID
    Sys->>DB: 1. updateOnPaidOrderToDw()
    Note right of DB: $inc (Inkremental pada DwReportOverall)
    Mgt->>Mgt: 2. Buka Laporan (v-model=time_filter)
    Mgt->>API: 3. @click="applyFilters"
    API->>DB: Fetch DwReport (Pre-Calculated)
    DB-->>API: Return JSON (Tanpa Loading Berat)
    API-->>Mgt: 4. Render Grafis Otomatis
