sequenceDiagram
    autonumber
    participant Pengunjung as Transaksi Selesai
    participant Sistem as Sistem Aplikasi
    actor Mgt as Management / Superadmin

    Pengunjung-->>Sistem: 1. Tiket lunas tercatat ke dalam sistem
    Note right of Sistem: Sistem diam-diam menambah<br/>angka penjualan tanpa proses manual tambahan
    Mgt->>Sistem: 2. Buka Menu "Laporan Keseluruhan"
    Mgt->>Sistem: 3. Mengubah Dropdown "Filter Waktu" (Harian/Bulanan)
    Mgt->>Sistem: 4. Klik Tombol "Terapkan Filter"
    Sistem-->>Mgt: 5. Mencetak Diagram Kue (Pie) & Diagram Batang<br/>(Pendapatan kotor vs Tunai) dengan cepat
