export const LAKOMI_TOKEN_ABI = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ type: "address", name: "account" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ type: "address", name: "to" }, { type: "uint256", name: "value" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ type: "address", name: "spender" }, { type: "uint256", name: "amount" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "registerMember", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "registerMemberAdmin", stateMutability: "nonpayable", inputs: [{ type: "address", name: "member" }], outputs: [] },
  { type: "function", name: "isRegisteredMember", stateMutability: "view", inputs: [{ type: "address", name: "account" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "getMemberCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getVotingPower", stateMutability: "view", inputs: [{ type: "address", name: "account" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getLockedBalance", stateMutability: "view", inputs: [{ type: "address", name: "account" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getAvailableBalance", stateMutability: "view", inputs: [{ type: "address", name: "account" }], outputs: [{ type: "uint256" }] },
] as const

export const LAKOMI_VAULT_ABI = [
  { type: "function", name: "deposit", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "amount" }], outputs: [{ type: "uint256", name: "sharesIssued" }] },
  { type: "function", name: "withdraw", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "amount" }], outputs: [{ type: "uint256", name: "actualAmount" }] },
  { type: "function", name: "requestWithdrawal", stateMutability: "nonpayable", inputs: [{ type: "address", name: "recipient" }, { type: "uint256", name: "amount" }], outputs: [{ type: "uint256", name: "withdrawalId" }] },
  { type: "function", name: "approveWithdrawal", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "withdrawalId" }], outputs: [] },
  { type: "function", name: "executeWithdrawal", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "withdrawalId" }], outputs: [] },
  { type: "function", name: "cancelWithdrawal", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "withdrawalId" }], outputs: [] },
  { type: "function", name: "paySimpananPokok", stateMutability: "nonpayable", inputs: [{ type: "address", name: "member" }], outputs: [] },
  { type: "function", name: "paySimpananWajib", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "receiveRevenue", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "amount" }], outputs: [] },
  { type: "function", name: "distributeSHU", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "claimSHU", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "distributionId" }], outputs: [] },
  { type: "function", name: "hasPaidSimpananPokok", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "getSimpananWajibPeriodsOwed", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "isSimpananWajibCurrent", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "bool" }] },
  {
    type: "function", name: "getSimpananSummary", stateMutability: "view",
    inputs: [{ type: "address", name: "member" }],
    outputs: [
      { type: "uint256", name: "pokok" },
      { type: "uint256", name: "wajibTotal" },
      { type: "uint256", name: "wajibPeriodsPaid" },
      { type: "uint256", name: "wajibPeriodsOwed" },
      { type: "uint256", name: "sukarela" },
      { type: "uint256", name: "totalContribution" },
    ],
  },
  { type: "function", name: "getMemberBalance", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getMemberSharePercent", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getMemberValue", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "contributionScore", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getContributionTier", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint8" }] },
  { type: "function", name: "getTotalAssets", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getPendingSHU", stateMutability: "view", inputs: [{ type: "address", name: "member" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "shuDistributionCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function", name: "shuDistributions", stateMutability: "view",
    inputs: [{ type: "uint256", name: "index" }],
    outputs: [
      { type: "uint256", name: "totalAmount" },
      { type: "uint256", name: "memberCount" },
      { type: "uint256", name: "timestamp" },
      { type: "uint256", name: "perShare" },
    ],
  },
  { type: "function", name: "accumulatedRevenue", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalShares", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "simpananPokokAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "simpananWajibAmount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
] as const

export const LAKOMI_GOVERN_ABI = [
  {
    type: "function", name: "createProposal", stateMutability: "nonpayable",
    inputs: [
      { type: "string", name: "description" },
      { type: "uint8", name: "proposalType" },
      { type: "address", name: "target" },
      { type: "uint256", name: "value" },
      { type: "bytes", name: "callData" },
    ],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "castVote", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "proposalId" }, { type: "uint8", name: "support" }], outputs: [] },
  { type: "function", name: "queue", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [] },
  { type: "function", name: "execute", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [] },
  { type: "function", name: "cancel", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [] },
  { type: "function", name: "vetoProposal", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [] },
  { type: "function", name: "scheduleAnnualRAT", stateMutability: "nonpayable", inputs: [{ type: "string", name: "description" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "state", stateMutability: "view", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [{ type: "uint8" }] },
  { type: "function", name: "quorum", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "isRATDue", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "proposalCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function", name: "getProposal", stateMutability: "view",
    inputs: [{ type: "uint256", name: "proposalId" }],
    outputs: [
      { type: "address", name: "proposer" },
      { type: "string", name: "description" },
      { type: "uint8", name: "proposalType" },
      { type: "uint256", name: "startTime" },
      { type: "uint256", name: "endTime" },
      { type: "uint256", name: "forVotes" },
      { type: "uint256", name: "againstVotes" },
      { type: "uint256", name: "abstainVotes" },
      { type: "bool", name: "executed" },
      { type: "bool", name: "canceled" },
      { type: "bool", name: "vetoed" },
    ],
  },
  { type: "function", name: "hasVoted", stateMutability: "view", inputs: [{ type: "uint256", name: "proposalId" }, { type: "address", name: "account" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "executionTimelock", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "proposalQueuedTime", stateMutability: "view", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "proposalTarget", stateMutability: "view", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [{ type: "address" }] },
  { type: "function", name: "proposalValue", stateMutability: "view", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "proposalCallData", stateMutability: "view", inputs: [{ type: "uint256", name: "proposalId" }], outputs: [{ type: "bytes" }] },
  { type: "function", name: "votingPeriod", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
] as const

export const LAKOMI_LOANS_ABI = [
  {
    type: "function", name: "requestLoan", stateMutability: "nonpayable",
    inputs: [{ type: "uint256", name: "amount" }, { type: "uint256", name: "duration" }, { type: "string", name: "reason" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "approveLoan", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "loanId" }], outputs: [] },
  { type: "function", name: "disburse", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "loanId" }], outputs: [] },
  { type: "function", name: "repay", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "loanId" }, { type: "uint256", name: "amount" }], outputs: [] },
  { type: "function", name: "repayInFull", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "loanId" }], outputs: [] },
  { type: "function", name: "calculateInterest", stateMutability: "view", inputs: [{ type: "uint256", name: "principal" }, { type: "uint256", name: "duration" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getMaxLoanAmount", stateMutability: "view", inputs: [{ type: "address", name: "borrower" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getRequiredCollateral", stateMutability: "view", inputs: [{ type: "uint256", name: "amount" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getBorrowerLoans", stateMutability: "view", inputs: [{ type: "address", name: "borrower" }], outputs: [{ type: "uint256[]" }] },
  {
    type: "function", name: "getLoan", stateMutability: "view",
    inputs: [{ type: "uint256", name: "loanId" }],
    outputs: [
      { type: "uint256", name: "id" },
      { type: "address", name: "borrower" },
      { type: "uint256", name: "principal" },
      { type: "uint256", name: "interest" },
      { type: "uint256", name: "collateralTokens" },
      { type: "uint256", name: "startTime" },
      { type: "uint256", name: "dueTime" },
      { type: "uint256", name: "repaidAmount" },
      { type: "uint256", name: "totalOwed" },
      { type: "uint256", name: "remaining" },
      { type: "uint8", name: "status" },
      { type: "string", name: "reason" },
    ],
  },
  { type: "function", name: "activeLoanCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "loanCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "markDefaulted", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "loanId" }], outputs: [] },
  { type: "function", name: "claimCollateral", stateMutability: "nonpayable", inputs: [{ type: "uint256", name: "loanId" }], outputs: [] },
  { type: "function", name: "interestRate", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "collateralRatio", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
] as const

export const USDC_ABI = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ type: "address", name: "account" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ type: "address", name: "to" }, { type: "uint256", name: "value" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ type: "address", name: "spender" }, { type: "uint256", name: "amount" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ type: "address", name: "owner" }, { type: "address", name: "spender" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "mint", stateMutability: "nonpayable", inputs: [{ type: "address", name: "to" }, { type: "uint256", name: "amount" }], outputs: [] },
] as const
